import { Tutor, WeeklyScheduleItem } from './types';

/**
 * Single source of truth for all mock data in TutorSlot.
 * All names, courses, locations, dates, and times are purely fictional academic examples.
 */

export const DAYS_OF_WEEK: Array<'Monday' | 'Tuesday' | 'Wednesday' | 'Thursday' | 'Friday'> = [
  'Monday',
  'Tuesday',
  'Wednesday',
  'Thursday',
  'Friday',
];

export const CURRENT_WEEK_DATES: Record<string, string> = {
  Monday: 'Mon, Sep 7',
  Tuesday: 'Tue, Sep 8',
  Wednesday: 'Wed, Sep 9',
  Thursday: 'Thu, Sep 10',
  Friday: 'Fri, Sep 11',
};

export const INITIAL_TUTORS: Tutor[] = [
  {
    id: 'tutor-1',
    name: 'Dr. Aris Thorne',
    subject: 'Microeconomic Theory & Game Design',
    level: 'UG',
    major: 'Economics',
    description: 'Specializes in mathematical modeling of competitive decision-making, consumer equilibrium, and oligopoly payoff matrices.',
    rating: 4.9,
    reviewCount: 38,
    avatarInitials: 'AT',
    avatarColor: 'bg-amber-700 text-amber-50',
    slots: [
      {
        id: 'slot-101',
        tutorId: 'tutor-1',
        day: 'Monday',
        dateStr: 'Mon, Sep 7',
        time: '09:30 AM – 10:30 AM',
        room: 'Study Suite 302',
        isBooked: false,
      },
      {
        id: 'slot-102',
        tutorId: 'tutor-1',
        day: 'Wednesday',
        dateStr: 'Wed, Sep 9',
        time: '02:00 PM – 03:00 PM',
        room: 'Academic Pavilion B',
        isBooked: false,
      },
      {
        id: 'slot-103',
        tutorId: 'tutor-1',
        day: 'Friday',
        dateStr: 'Fri, Sep 11',
        time: '11:00 AM – 12:00 PM',
        room: 'Study Suite 302',
        isBooked: false,
      },
    ],
    profile: {
      title: 'Associate Professor of Economics',
      department: 'School of Economics',
      education: [
        'Ph.D. in Economics, London School of Economics',
        'M.Sc. in Econometrics & Mathematical Economics, Oxford University',
        'B.Sc. (Hons) in Quantitative Economics, National University of Singapore',
      ],
      background: 'Over 12 years of research across applied game theory, regulatory auction mechanism design, and strategic corporate pricing behavior. Consulted for competition commissions across Southeast Asia.',
      teachingExperience: 'Taught Undergraduate Intermediate Microeconomics, Game Theory for Decision Makers, and Advanced Industrial Organization at SMU and LSE over 9 academic years. Awarded the Dean’s Teaching Excellence Award in 2024.',
      publications: [
        'Thorne, A. & Tan, L. (2024). "Repeated Dynamic Auctions with Asymmetric Risk Tolerances." Journal of Economic Theory, 189, 105-132.',
        'Thorne, A. (2022). "Collusion Vulnerability in Multi-Unit Spectrum Allocations." International Journal of Industrial Organization, 74, 45-68.',
        'Lim, C. & Thorne, A. (2020). "Signaling Equilibria in Bilateral Duopolies." Review of Economic Studies, 87(3), 1140-1168.',
      ],
      officeLocation: 'School of Economics, Level 5, Room 5012',
      email: 'aristhorne@smu.edu.sg',
    },
  },
  {
    id: 'tutor-2',
    name: 'Nadia Chen-Vazquez',
    subject: 'Organic Reaction Pathways & Synthesis',
    level: 'UG',
    major: 'Chemical Sciences',
    description: 'Assisting students through carbonyl additions, chiral stereochemistry, and multi-step retro-synthetic laboratory strategies.',
    rating: 4.8,
    reviewCount: 42,
    avatarInitials: 'NC',
    avatarColor: 'bg-emerald-700 text-emerald-50',
    slots: [
      {
        id: 'slot-201',
        tutorId: 'tutor-2',
        day: 'Monday',
        dateStr: 'Mon, Sep 7',
        time: '01:30 PM – 02:30 PM',
        room: 'Science Hall 118',
        isBooked: false,
      },
      {
        id: 'slot-202',
        tutorId: 'tutor-2',
        day: 'Tuesday',
        dateStr: 'Tue, Sep 8',
        time: '10:00 AM – 11:00 AM',
        room: 'Science Hall 118',
        isBooked: false,
      },
      {
        id: 'slot-203',
        tutorId: 'tutor-2',
        day: 'Thursday',
        dateStr: 'Thu, Sep 10',
        time: '03:30 PM – 04:30 PM',
        room: 'Chemistry Hub 2A',
        isBooked: false,
      },
    ],
    profile: {
      title: 'Senior Lecturer in Molecular Chemistry',
      department: 'College of Science & Technology',
      education: [
        'Ph.D. in Organic Chemistry, UC Berkeley',
        'B.S. in Chemical Biology (Summa Cum Laude), Cornell University',
      ],
      background: 'Synthetic organic chemist specializing in transition-metal-catalyzed cross-coupling reactions, stereoselective biocatalysis, and green laboratory reagent optimization.',
      teachingExperience: '8 years instructing foundational and intermediate organic chemistry lecture series, leading high-throughput laboratory practicals, and mentoring honors thesis candidates.',
      publications: [
        'Chen-Vazquez, N. et al. (2025). "Mild Nickel-Catalyzed Enantioselective C-C Bond Formations." Journal of the American Chemical Society, 147(4), 2210-2224.',
        'Chen-Vazquez, N. & Gomez, R. (2023). "Solvent-Free Retro-Synthetic Strategies in Educational Labs." Green Chemistry Letters & Reviews, 16(1), 89-102.',
      ],
      officeLocation: 'Science Complex West, Level 3, Lab Suite 314',
      email: 'nadiachen@smu.edu.sg',
    },
  },
  {
    id: 'tutor-3',
    name: 'Devon K. Mercer',
    subject: 'Vector Calculus & Differential Systems',
    level: 'UG',
    major: 'Applied Mathematics',
    description: 'Patient approach covering Stokes theorem, double integration, vector fields, and linear boundary value problems.',
    rating: 5.0,
    reviewCount: 51,
    avatarInitials: 'DM',
    avatarColor: 'bg-blue-700 text-blue-50',
    slots: [
      {
        id: 'slot-301',
        tutorId: 'tutor-3',
        day: 'Tuesday',
        dateStr: 'Tue, Sep 8',
        time: '01:00 PM – 02:00 PM',
        room: 'Math Learning Bay 4',
        isBooked: false,
      },
      {
        id: 'slot-302',
        tutorId: 'tutor-3',
        day: 'Thursday',
        dateStr: 'Thu, Sep 10',
        time: '11:00 AM – 12:00 PM',
        room: 'Math Learning Bay 4',
        isBooked: false,
      },
    ],
    profile: {
      title: 'Principal Fellow in Mathematics & Modeling',
      department: 'Department of Mathematical Sciences',
      education: [
        'Ph.D. in Applied Mathematics, University of Cambridge (DAMTP)',
        'M.Math. (Master of Mathematics, First Class), Cambridge Tripos Part III',
      ],
      background: 'Research encompasses computational fluid dynamics, Navier-Stokes approximations, and topological vector field decomposition. Industry consultant on aerodynamic simulation solvers.',
      teachingExperience: '11 years teaching Multivariable Calculus, Ordinary & Partial Differential Equations, and Real Analysis. Recipient of 3 university-wide Outstanding Educator Commendations.',
      publications: [
        'Mercer, D. K. & Wallace, P. (2024). "Vorticity Preservation Algorithms for Complex Boundary Manifolds." Journal of Computational Physics, 492, 112-140.',
        'Mercer, D. K. (2021). "Iterative Eigen-solvers for High-Dimensional Differential Systems." SIAM Journal on Applied Mathematics, 81(5), 2004-2028.',
      ],
      officeLocation: 'Mathematical Institute, Level 4, Office 412',
      email: 'devonmercer@smu.edu.sg',
    },
  },
  {
    id: 'tutor-4',
    name: 'Soren Lindqvist',
    subject: 'Data Structures & Algorithmic Complexity',
    level: 'UG',
    major: 'Computer Science',
    description: 'Demystifying asymptotic Big-O bounds, graph traversals (BFS/DFS), dynamic programming tables, and heap indexing.',
    rating: 4.9,
    reviewCount: 64,
    avatarInitials: 'SL',
    avatarColor: 'bg-indigo-700 text-indigo-50',
    slots: [
      {
        id: 'slot-401',
        tutorId: 'tutor-4',
        day: 'Monday',
        dateStr: 'Mon, Sep 7',
        time: '04:00 PM – 05:00 PM',
        room: 'Computing Lab 405',
        isBooked: false,
      },
      {
        id: 'slot-402',
        tutorId: 'tutor-4',
        day: 'Wednesday',
        dateStr: 'Wed, Sep 9',
        time: '10:30 AM – 11:30 AM',
        room: 'Computing Lab 405',
        isBooked: false,
      },
      {
        id: 'slot-403',
        tutorId: 'tutor-4',
        day: 'Friday',
        dateStr: 'Fri, Sep 11',
        time: '02:30 PM – 03:30 PM',
        room: 'Computing Lab 405',
        isBooked: false,
      },
    ],
    profile: {
      title: 'Associate Professor of Computer Science',
      department: 'School of Computing and Information Systems',
      education: [
        'Ph.D. in Computer Science, ETH Zurich',
        'M.Sc. in Distributed Systems, KTH Royal Institute of Technology',
      ],
      background: 'Expertise in high-performance graph processing, probabilistic data structures (Bloom filters, HyperLogLog), and cache-aware algorithm engineering. Former visiting researcher at Google Brain Zurich.',
      teachingExperience: 'Over 10 years instructing Data Structures & Algorithms, Design of Operating Systems, and Advanced Distributed Storage. Creator of interactive automated algorithm grading harnesses.',
      publications: [
        'Lindqvist, S. & Bach, E. (2025). "Lock-Free Subgraph Isomorphism at Scale." IEEE Transactions on Parallel and Distributed Systems, 36(2), 341-356.',
        'Lindqvist, S. (2023). "Cache-Conscious Priority Queues for Streaming Graph Traversal." ACM Transactions on Algorithms (TALG), 19(3), 1-28.',
        'Lindqvist, S. & Wu, K. (2021). "Near-Optimal Dynamic Programming for Constrained Shortest Paths." Algorithmica, 83, 1580-1612.',
      ],
      officeLocation: 'SCIS Building 1, Level 4, Room 4028',
      email: 'sorenl@smu.edu.sg',
    },
  },
  {
    id: 'tutor-5',
    name: 'Helena Rostova',
    subject: 'Critical Writing & Scholarly Arguments',
    level: 'UG',
    major: 'Humanities & Literature',
    description: 'Editorial coaching on thesis refinement, structural paragraph transitions, textual counterarguments, and citation precision.',
    rating: 4.8,
    reviewCount: 29,
    avatarInitials: 'HR',
    avatarColor: 'bg-rose-700 text-rose-50',
    slots: [
      {
        id: 'slot-501',
        tutorId: 'tutor-5',
        day: 'Tuesday',
        dateStr: 'Tue, Sep 8',
        time: '03:00 PM – 04:00 PM',
        room: 'Humanities Lounge 204',
        isBooked: false,
      },
      {
        id: 'slot-502',
        tutorId: 'tutor-5',
        day: 'Thursday',
        dateStr: 'Thu, Sep 10',
        time: '09:00 AM – 10:00 AM',
        room: 'Humanities Lounge 204',
        isBooked: false,
      },
    ],
    profile: {
      title: 'Senior Faculty Fellow in Academic Discourse',
      department: 'School of Social Sciences & Humanities',
      education: [
        'Ph.D. in English Literature & Rhetoric, Columbia University',
        'M.A. in Comparative Critical Theory, University of Chicago',
        'B.A. in English (First Class), Yale University',
      ],
      background: 'Specialist in 20th-century rhetoric, philosophical argumentation, and interdisciplinary writing pedagogy. Editorial board member for Modern Critical Studies.',
      teachingExperience: '14 years directing undergraduate university writing seminars, graduate dissertation workshops, and interdisciplinary publishing roundtables.',
      publications: [
        'Rostova, H. (2024). "The Architectonics of Modern Scholarly Prose." Critical Inquiry, 50(2), 241-267.',
        'Rostova, H. & Sterling, M. (2022). "Rhetorical Stances and Counter-Attribution in Academic Peer Review." College Composition and Communication, 73(4), 610-639.',
      ],
      officeLocation: 'Humanities Hall, Level 2, Suite 210',
      email: 'hrostova@smu.edu.sg',
    },
  },
  {
    id: 'tutor-6',
    name: 'Tariq Al-Sabah',
    subject: 'Corporate Financial Statement Modeling',
    level: 'PG',
    major: 'Finance & Accounting',
    description: 'Hands-on breakdown of discounted cash flows (DCF), debt amortization schedules, working capital cycles, and ratios.',
    rating: 4.9,
    reviewCount: 47,
    avatarInitials: 'TA',
    avatarColor: 'bg-teal-700 text-teal-50',
    slots: [
      {
        id: 'slot-601',
        tutorId: 'tutor-6',
        day: 'Wednesday',
        dateStr: 'Wed, Sep 9',
        time: '04:30 PM – 05:30 PM',
        room: 'Finance Commons 108',
        isBooked: false,
      },
      {
        id: 'slot-602',
        tutorId: 'tutor-6',
        day: 'Friday',
        dateStr: 'Fri, Sep 11',
        time: '09:00 AM – 10:00 AM',
        room: 'Finance Commons 108',
        isBooked: false,
      },
    ],
    profile: {
      title: 'Professor of Practice in Corporate Finance',
      department: 'Lee Kong Chian School of Business',
      education: [
        'Ph.D. in Finance, Wharton School of Business (Univ. of Pennsylvania)',
        'MBA (Finance Concentration), INSEAD',
        'CFA Charterholder, CFA Institute',
      ],
      background: '15 years of industry experience across global investment banking (M&A Advisory) and private equity in London, Dubai, and Singapore prior to entering academia full-time.',
      teachingExperience: '10 years instructing MBA and Master of Science in Applied Finance students on LBO Modeling, Mergers & Acquisitions valuation, and Credit Portfolio structuring. Named MBA Professor of the Year in 2023.',
      publications: [
        'Al-Sabah, T. & Al-Mansoor, F. (2024). "Cross-Border Valuation Distortions in Emerging Market LBOs." Journal of Financial Economics, 151, 103-128.',
        'Al-Sabah, T. (2022). "Synergy Realization and Debt Covenant Design in High-Leverage Transactions." Journal of Corporate Finance, 72, 102-124.',
      ],
      officeLocation: 'LKCSB Building, Level 4, Office 4085',
      email: 'tariqalsabah@smu.edu.sg',
    },
  },
  {
    id: 'tutor-7',
    name: 'Kavita Sundaram',
    subject: 'Experimental Psychology & Hypothesis Testing',
    level: 'PG',
    major: 'Psychological Science',
    description: 'Guiding undergraduates through ANOVA variance partitions, statistical regression interpretations, and survey validity checks.',
    rating: 4.7,
    reviewCount: 33,
    avatarInitials: 'KS',
    avatarColor: 'bg-violet-700 text-violet-50',
    slots: [
      {
        id: 'slot-701',
        tutorId: 'tutor-7',
        day: 'Tuesday',
        dateStr: 'Tue, Sep 8',
        time: '11:30 AM – 12:30 PM',
        room: 'Behavioral Lab 309',
        isBooked: false,
      },
      {
        id: 'slot-702',
        tutorId: 'tutor-7',
        day: 'Thursday',
        dateStr: 'Thu, Sep 10',
        time: '01:30 PM – 02:30 PM',
        room: 'Behavioral Lab 309',
        isBooked: false,
      },
    ],
    profile: {
      title: 'Associate Professor of Behavioral Science & Quantitative Methods',
      department: 'School of Social Sciences',
      education: [
        'Ph.D. in Cognitive & Quantitative Psychology, Stanford University',
        'M.S. in Applied Statistics, Stanford University',
        'B.A. (First Class Honours) in Psychology, University of Melbourne',
      ],
      background: 'Pioneered research into cognitive heuristics, Bayesian decision models in high-stress environments, and robust psychometric instrument design for organizational settings.',
      teachingExperience: '9 years teaching Postgraduate Multivariate Statistics, Experimental Design & Analysis, and Structural Equation Modeling (SEM) across graduate degree cohorts.',
      publications: [
        'Sundaram, K. & Thorne, A. (2025). "Decision Latency and Probability Discounting under Cognitive Load." Psychological Review, 132(1), 180-205.',
        'Sundaram, K. (2023). "Replicability and Mixed-Effects Modeling in Multi-Site Behavioral Experiments." Journal of Experimental Psychology: General, 152(6), 1640-1662.',
        'Sundaram, K. & Rao, V. (2021). "Psychometric Construct Invariance in Cross-Cultural Workplace Surveys." Journal of Applied Psychology, 106(8), 1210-1234.',
      ],
      officeLocation: 'Social Sciences Building, Level 3, Lab 322',
      email: 'kavitasundaram@smu.edu.sg',
    },
  },
];

/**
 * Initial student weekly tutoring schedule (empty until slots are booked).
 * Only booked tutoring sessions appear in My Week.
 */
export const INITIAL_STUDENT_SCHEDULE: WeeklyScheduleItem[] = [];
